[workspace]

[package]
name = "keyed-signal-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos-signals = { path = "../.." }
leptos = { default-features = false, features = ["serde"], version = "0.0" }
leptos_meta = { default-features = false, version = "0.0" }
leptos_router = { default-features = false, version = "0.0" }

gloo-net = { version = "0.2", features = ["http"] }
gloo-timers = { version = "0.2", features = ["futures"] }
log = "0.4"
cfg-if = "1.0"
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }

# dependecies for client (enable when csr or hydrate set)
wasm-bindgen = { version = "0.2", optional = true }
console_log = { version = "0.2", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }

# dependecies for server (enable when ssr set)
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", features = ["macros"], optional = true }
futures = { version = "0.3", optional = true }
simple_logger = { version = "4.0", optional = true }
reqwest = { version = "0.11", features = ["json"], optional = true }

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[features]
leptos_autoreload = []
default = ["ssr"]
hydrate = [
  "leptos/hydrate",
  "leptos_meta/hydrate",
  "leptos_router/hydrate",
  "dep:wasm-bindgen",
  "dep:console_log",
  "dep:console_error_panic_hook",
]
csr = [
  "leptos/csr",
  "leptos_meta/csr",
  "leptos_router/csr",
  "dep:wasm-bindgen",
  "dep:console_log",
  "dep:console_error_panic_hook",
]
ssr = [
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "dep:reqwest",
  "dep:actix-web",
  "dep:actix-files",
  "dep:futures",
  "dep:simple_logger",
]

[package.metadata.leptos]
# Path, relative to root, to generat rust code to
gen_file = "src/server/generated.rs"
# Path to the source index.html file
index_file = "index.html"
# [Optional] Files in the asset_dir will be copied to the target/site directory
# assets_dir = "assets"
# [Optional] Command to use when running end2end tests. It will run in the end2end dir.
# end2end_test_cmd = "npx playwright test"
# On which port to serve the client side rendered site (when using --csr option)
csr_port = 3000
# The port to use for automatic reload monitoring
reload_port = 3001

[package.metadata.leptos.style]
# Main style file. If scss or sass then it will be compiled to css.
# the parent folder will be watched for changes
file = "style/main.scss"
# A https://browsersl.ist query
browserquery = "defaults"
